#! /bin/bash

repos="matematikk-mooc.github.io mmooc-docker-postgresql mmooc-docker-redis mmooc-docker-canvas mmooc-docker canvas-lms mmooc-docker-haproxy"

case $1 in
    clone)
        for X in $repos; do
            git clone git@github.com:matematikk-mooc/$X.git
        done

        cd canvas-lms
        git remote add upstream git@github.com:instructure/canvas-lms.git
        cd -
        ;;
    *)
        for X in ". $repos"; do
            echo Entering $X
            (cd $X && git $@)
        done
esac
