#! /bin/bash

repos="matematikk-mooc.github.io mmooc-docker-postgresql mmooc-docker-redis mmooc-docker-canvas mmooc-docker canvas-lms mmooc-docker-haproxy mmooc-docker-tools"
all_repos=". $repos"

case $1 in
    clone)
        for X in $repos; do
            if ! [ -e $X ]; then 
                git clone git@github.com:matematikk-mooc/$X.git
            fi
        done

        cd canvas-lms
        if ! git remote | grep -q upstream; then
            git remote add upstream git@github.com:instructure/canvas-lms.git
        fi
        cd -
        ;;
    each)
        for X in $all_repos; do
            cd $X
            if [ -n "$(git status --porcelain)" ]; then
                git status -s
                env PS1="$X> " bash --noprofile --norc
            fi
            cd -
        done
        ;;
    help)
        cat <<EOF
Usage: ./mgit COMMAND

Commands:
           (no command) Call git with the given arguments on all repos
    clone  Clone all repos from Github/matematikk-mooc
    each   Run a subshell in each folder that have uncommited changes
EOF
        ;;
    *)
        for X in $all_repos; do
            echo Entering $X
            (cd $X && git "$@")
        done
        ;;
esac
