#! /bin/bash

repos="matematikk-mooc.github.io mmooc-docker-postgresql mmooc-docker-redis mmooc-docker-canvas mmooc-docker canvas-lms mmooc-docker-haproxy"

case $1 in
    clone)
        for X in $repos; do
            if ! [ -e $X ]; then 
                git clone git@github.com:matematikk-mooc/$X.git
            fi
        done

        cd canvas-lms
        if ! git remote | grep -q upstream; then
            git remote add upstream git@github.com:instructure/canvas-lms.git
        fi
        cd -
        ;;
    *)
        list=". $repos"
        for X in $list; do
            echo Entering $X
            (cd $X && git "$@")
        done
esac
