#!/usr/bin/env bash
set -u

echo "Finding network ports for the container named 'web'"

port=$(docker port web 80 | cut -d: -f2)

if which docker-machine >/dev/null 2>&1
then
  echo "Found \"docker-machine\", guessing you're not on Linux. Getting ip address from VM."
  addr=$(docker-machine ip)
else
  echo "No \"docker-machine\" found, guessing you're on Linux. Using localhost."
  addr="127.0.0.1"
fi

echo ""
echo "Canvas address: http://${addr}:${port}/"
